export enum CardImages {
  angular = 'angular',
  d3 = 'd3',
  jenkins = 'jenkins',
  postcss = 'postcss',
  react = 'react',
  redux = 'redux',
  sass = 'sass',
  splendex = 'splendex',
  ts = 'ts',
  webpack = 'webpack',
  js = 'js',
  csharp = 'csharp',
  netcore = 'netcore',
  linus = 'linus',
  gitlogo = 'gitlogo',
}
